# Generated by Django 6.0.2 on 2026-02-17 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1880)])),
                ('cover', models.ImageField(upload_to='covers')),
                ('imdb_link', models.URLField()),
                ('watched', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(related_name='movies_by_genre', to='movies.genre')),
                ('tags', models.ManyToManyField(blank=True, related_name='movies_by_tag', to='movies.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
